spring:
  application:
    name: discovery
server:
  port: 8761


eureka:
  instance:
    hostname: viniciuscluna-discovery.herokuapp.com
    home-page-url: https://${eureka.instance.hostName}/
    home-page-url-path: https://${eureka.instance.hostName}
  client:
    serviceUrl:
      defaultZone: https://viniciuscluna-discovery.herokuapp.com/eureka/
      non-secure-port: 80
      secure-port: 443
    fetch-registry: false
    register-with-eureka: false