spring:
  application:
    name: discovery
server:
  port: 8761


eureka:
  instance:
    hostname: viniciuscluna-discovery.herokuapp.com
    non-secure-port: 80
  client:
    fetch-registry: false
    register-with-eureka: false